apiVersion: v1
kind: PersistentVolume
metadata:
  name: efk-pv
  namespace: logging
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  storageClassName: efk-sc  
  hostPath:
    path: "/usr/share/elasticsearch/data"
