apiVersion: v1
kind: Service
metadata: 
  name: app-service
  labels:
    app: petclinic
    environment: dev
  namespace: petclinic
spec:
  type: NodePort
  selector:
    app: petclinic
  ports:
  - name: app
    protocol: "TCP"
    port: 8080    
