apiVersion: app/v1
kind: Deployment
metadata:
  name: petclinic-app
  labels:
    app: petclinic
    environment: dev
  namespace: petclinic  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%    
  template:
    metadata:
      name: petclinic-app
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: gkiran04/petclinic:39
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
