apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  labels:
    app: petclinic
    environment: dev
  namespace: petclinic  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  strategy:
    type: RollingUpdate
    
  template:
    metadata:
      name: petclinic-app
      labels:
        app: petclinic
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: petclinic
        image: 001285825849.dkr.ecr.us-east-1.amazonaws.com/petclinic:32
        env:
        - name: MYSQL_URL
          value: "jdbc:mysql://db-service:3306/petclinic"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-user
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-password       
        ports:
        - containerPort: 8080
          protocol: "TCP"
        imagePullPolicy: Always
      
