apiVersion: v1
kind: StorageClass
metadata:
  name: standard
  labels:
    app: petclinic
    environment: dev
  namespace: petclinic
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate  