apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: db-hpa
  namespace: petclinic
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: petclinic-db
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  
