apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: petclinic
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  storageClassName: standard  
  hostPath:
    path: "/var/lib/mysql"    
