apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: petclinic-db
  labels:
    app: petclinic-db
    environment: dev
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-db
  serviceName: db-service
  template:
    metadata:
      name: petclinic-db
      labels:
        app: petclinic-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:8.0
        imagePullPolicy: Always
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-password 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-root-password 
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-name             
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts: 
        - name: db-volume
          mountPath: "/var/lib/mysql"   
  volumeClaimTemplates:
  - metadata:
      name: db-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi 
      volumeName: db-pv
      storageClassName: standard          
