apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
  labels:
    app: petclinic
    environment: dev
  namespace: petclinic  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    
  template:
    metadata:
      name: petclinic-app
      labels:
        app: petclinic
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: petclinic
        image: 001285825849.dkr.ecr.us-east-1.amazonaws.com/petclinic:32
        env:
        - name: MYSQL_URL
          value: "jdbc:mysql://myapp-db.cwex7cgc1g2r.us-east-1.rds.amazonaws.com:3306/petclinic"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-user
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-password       
        ports:
        - containerPort: 8080
          protocol: "TCP"
        imagePullPolicy: Always
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 10.96.0.10
        searches:
        - petclinic.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        - asia-south1-c.c.practical-proxy-389909.internal 
        - c.practical-proxy-389909.internal
        - google.internal
