apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: petclinic
type: Opaque
data:
  db-user: cGV0Y2xpbmlj
  db-password: cGV0Y2xpbmlj
  db-name: cGV0Y2xpbmlj
  db-root-password: cm9vdA==
    
